import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  alegreya,
  danfoRegular,
  inter,
  lusitana,
  permanentMarker,
} from "@/app/fonts/fonts";
import "./globals.css";
import Provider from "@/lib/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${lusitana.variable} ${alegreya.variable} ${danfoRegular.variable} ${permanentMarker.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
