import type { Metadata } from "next";
import Header from "@/app/(main)/ui/header";
import Footer from "@/app/(main)/ui/footer";
import "@/app/(main)/style.css";
import { validateRequest } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Main Page",
  description: "Generated by create next app",
};

export default async function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user } = await validateRequest();

  return (
    <div className="max-w-screen-xl m-auto px-2 md:px-6">
      <div className="">
        <Header />
      </div>
      <div className="md:p-6 p-2">{children}</div>
      <Footer user={user} />
    </div>
  );
}
